language: node_js
node_js:
  - "node"
deploy:
    GH_TOKEN: 6fe07eb9b962df554c80f6f7d563374d3ed269a1  # Set in the settings page of your repository, as a secure variable
  - skip_cleanup: true
    provider: script
    script: npm run deploy
    on:
      branch: master
  - skip_cleanup: true
    provider: script
    script: npm run deploy-branch
    on:
      all_branches: true
      condition: '"$TRAVIS_BRANCH" != "master" && "$TRAVIS_BRANCH" != "gh-pages"'
